renegade-fi/renegade-frontend

- app/trade/[base]/components/charts/fill-chart.tsx
- app/trade/[base]/components/order-details/details-content.tsx
- components/dialogs/new-order-stepper/steps/default.tsx
- hooks/use-prepare-create-order.ts
- lib/order.ts
- lib/utils.ts
- package.json
- pnpm-lock.yaml
This PR bumps the SDK to a version that supports specifying the worst case price for safety. It sets a default worst case price of 50% of the Binance price for sell orders, and 150% for buy orders.
Tested using the frontend by buying / selling all available tokens and ensuring that I received a fill for each.
> order: include worst case price

- app/orders/columns.tsx
- app/trade/[base]/components/order-details/details-content.tsx
- app/trade/[base]/components/order-details/empty-content.tsx
- app/trade/[base]/components/order-details/insufficient-warning.tsx
- hooks/use-check-insufficient-balances-for-order.tsx
This PR adds an indicator icon to rows in the order table that is visible if there is not enough balance to fill the order. It also adds a trigger to the warning in the order details sheet to open the transfer dialog with the correct token set for easy depositing.
Tested locally and using a preview deploy.
> order table: add indicator for under capitalized orders

- app/api/get-maintenance-mode/route.ts
- app/components/maintenance-banner.tsx
- app/layout.tsx
- app/orders/data-table.tsx
- app/trade/[base]/components/new-order/new-order-form.tsx
- app/trade/[base]/components/order-details/cancel-button.tsx
- app/trade/[base]/page-client.tsx
- components/dialogs/transfer/transfer-dialog.tsx
- components/ui/responsive-tooltip.tsx
- hooks/use-maintenance-mode.ts
- package.json
- pnpm-lock.yaml
This PR adds the ability to put the interface in "maintenance mode" where on-chain actions are disabled when the maintenance flag is on (using environment variables).
Tested locally and in preview deployments.
> app: add maintenance mode

- app/orders/columns.tsx
This PR fixes a bug in the tooltip for undercapitalized orders that was displaying the incorrect token ticker.
> order table: fix order indicator side

- app/orders/columns.tsx
- app/trade/[base]/components/order-details/details-content.tsx
This PR fixes an issue when determining if an order was undercapitalized or not.
> order details: use remaining amount for insufficient balance calculation

- app/components/deposit-banner.tsx
This PR prevents the deposit banner from being closed through user interaction. Now, the only way to hide it is to deposit funds. This is to aid users in the onboarding process.
> deposit banner: remove close button

- components/dialogs/transfer/transfer-dialog.tsx
This PR fixes a text wrap issue in the footer button of the transfer dialog.
> transfer dialog: wrap footer button if needed

- app/stats/charts/volume-chart.tsx
- app/stats/page.tsx
This PR opts `/stats` page out of static rendering. According to the Next.js docs: ```If you prefer not to pass additional options to fetch, like cache: 'no-store', next: { revalidate: 0 } or in cases where fetch is not available, you can use noStore() as a replacement for all of these use cases.```
> stats: opt out of static rendering

- app/stats/page.tsx
This PR unsets fetchCache and unstable_noStore config options that ultimately do not have any affect on the caching of requests to the KV database.
> stats: unset fetchCache + unstable_noStore

- package.json
- pnpm-lock.yaml
This PR bumps the Renegade SDK to v0.3.3 which has support for `min_fill_size` field on the Order struct.
> chore: bump sdk

- lib/utils.ts
This PR adjusts external links from the BBO banner to ensure that Binance and OKX point to the WBTC charts.
> bbo banner: Remap BTC to wBTC

- app/trade/[base]/components/settings-dropdown.tsx
This PR uses media queries to determine if the app is being run in a PWA (in standalone display mode) and hides the "Install Mobile App" button if so.
> settings dropdown: hide pwa button if in pwa

- app/components/task-toaster.tsx
- components/dialogs/transfer/transfer-dialog.tsx
This PR starts a `payFees` task if there are more than 2 balances with fees. Also renders toasts for withdraw tasks in Queued states, and makes sure they last for 10s (longer than the default toast duration).
> transfer dialog: pay fees and render withdraw toast

- app/orders/columns.tsx
- app/trade/[base]/components/new-order/deposit-warning.tsx
- app/trade/[base]/components/new-order/new-order-form.tsx
- lib/constants/tooltips.ts
This PR makes improvements to order status and order placement when the user has little or no balances.
> orders: improve visibility of unfillable orders

- app/orders/columns.tsx
This PR shows "Undercapitalized" if the user's current balance is less than `order.amount`.
> order table: fix undercapitalized calc

- app/orders/columns.tsx
- app/trade/[base]/components/order-details/insufficient-warning.tsx
- hooks/use-is-order-undercapitalized.tsx
- lib/constants/tooltips.ts
This PR standardizes order undercapitalized checks using the hook. The term 'insufficient' was replaced with 'undercapitalized' for more clarity.
> fix: replace insufficient with undercapitalized

- app/api/get-logs/route.ts
This PR constructs a raw request to the RPC node to fetch logs to prevent caching.
> route: prevent cache storage on get logs fetch

- app/api/amberdata/price/route.ts
- app/api/amberdata/route.ts
- app/api/amberdata/token-prices/route.ts
- app/api/get-logs/route.ts
- app/api/savings/helpers.ts
- app/api/stats/external-transfer-logs/route.ts
- app/api/stats/historical-volume-kv/route.ts
- app/api/stats/net-flow/route.ts
- app/api/stats/set-historical-volume-kv/route.ts
- app/api/stats/set-inflow-kv/route.ts
- app/api/stats/set-net-flow-kv/route.ts
- app/api/stats/tvl/route.ts
- app/api/utils.ts
- app/lib/kv-utils.ts
- app/stats/hooks/use-cumulative-volume.ts
- app/stats/hooks/use-token-prices.ts
- app/stats/hooks/use-volume-data.ts
- hooks/use-combined-balances.ts
- tsconfig.json
This PR removes cache related options (fetch API and Next serverless functions) because in Next.js 15 fetch requests are no longer cached by default (neither are GET requests).
> chore: remove cache related directives

- components/dialogs/transfer/network-select.tsx
- components/dialogs/transfer/review-bridge.tsx
- components/dialogs/transfer/usdc-form.tsx
This PR ensures networks options are displayed iff a nonzero token balance exists on that chain. Additionally, bridge quotes for Solana are fetched iff a Solana wallet address is available.
> usdc form: conditionally display network options

- app/trade/[base]/components/new-order/deposit-warning.tsx
- app/trade/[base]/components/new-order/new-order-form.tsx
- components/dialogs/order-stepper/desktop/new-order-stepper.tsx
This PR prevents the flash of "Insufficient Balances" warning due to wallet data having to hydrate after page load.
> order form: prevent flash of insufficient balances to place order

- app/trade/[base]/components/new-order/new-order-form.tsx
This PR prevents the denomination switch button from populating a "0" in the input box when there was no previous input to convert.
> order form: prevent setting 0 amount when converting

- app/trade/[base]/components/new-order/fees-sections.tsx
- components/dialogs/order-stepper/desktop/new-order-stepper.tsx
- components/dialogs/order-stepper/desktop/steps/default.tsx
- components/dialogs/order-stepper/ioi-section.tsx
- components/dialogs/order-stepper/mobile/steps/confirm.tsx
- components/ui/checkbox.tsx
- hooks/use-prepare-create-order.ts
- lib/constants/articles.ts
This PR adds sections to the order placement flow where users can opt-in to enabling external matching on an order.
Tested locally and in preview deployment, made sure orders are placed with `allow_external_matches` set to `true`.
> order form: add external match option

- components/dialogs/order-stepper/desktop/new-order-stepper.tsx
This PR ensures the external orders option is only available when placing an order, not during the success step.
> order panel: show external orders option only when placing order

- app/components/maintenance-banner.tsx
- app/orders/data-table.tsx
- app/trade/[base]/components/new-order/new-order-form.tsx
- app/trade/[base]/components/order-details/cancel-button.tsx
- components/dialogs/transfer/default-form.tsx
- components/dialogs/transfer/usdc-form.tsx
- components/dialogs/transfer/weth-form.tsx
- components/ui/maintenance-button-wrapper.tsx
- hooks/use-maintenance-mode.ts
- lib/constants/maintenance.ts
This PR unifies logic regarding maintenance mode and also ensures it is only active in prod (not testnet).
TODO:
> maintenance mode: use maintenance wrapper for buttons

- components/dialogs/transfer/default-form.tsx
- components/dialogs/transfer/usdc-form.tsx
- components/dialogs/transfer/weth-form.tsx
- providers/wagmi-provider/wagmi-provider.tsx
This PR prevents a check meant to ensure the connected wallet was compatible with the app but was preventing the wallet from ever switching chains.
> transfer dialog: allow chain switch when approving eth bridge

- providers/state-provider/server-store-provider.tsx
- providers/state-provider/server-store.ts
This PR manually hydrates the server store to avoid this error:
```
Error: Server Functions cannot be called during initial render. This would create a fetch waterfall. Try to use a Server Component to pass data to Client Components instead.
```
> storage: manually rehydrate store on mount

- providers/wagmi-provider/wagmi-provider.tsx
This PR ensures that a user's Renegade wallet and Wagmi wallet are kept in sync by handling the case where the Wagmi wallet is unreachable but a Renegade wallet is in memory. This makes sure the entire UI shows correct data based on the connected wallet.
> wagmi: disconnect renegade wallet if wagmi wallet is locked/disconnected

- package.json
- pnpm-lock.yaml
This PR uses the SDK version that does _not_ fetch the token mapping at the top-level, and instead maintains that the frontend should load its token mapping from a stringified JSON env var
> chore: bump sdk deps

- app/trade/[base]/page-client.tsx
This PR debounces the callback invoked when resizing panels to optimize setting cookie storage.
> trade: debounce onLayout callback when resizing panels

- app/api/stats/cumulative-volume/route.ts
- app/api/stats/historical-volume/route.ts
- app/api/stats/set-historical-volume-kv/route.ts
- app/assets/page-client.tsx
- app/components/order-toaster.tsx
- app/components/task-history-sheet.tsx
- app/components/wallet-sidebar/hooks/use-unviewed-fills.ts
- app/environment.d.ts
- hooks/use-order-history.ts
- hooks/use-order-table-data.ts
- hooks/use-task-history.ts
- hooks/use-wait-for-task.ts
- package.json
- pnpm-lock.yaml
This PR replaces the `useOrderHistory` and `useTaskHistory` hooks from the SDK w/ a version that queries the historical state engine, an internal service that makes historical state previously managed by the relayer more reliable & durable.
> hooks: historical state client order & task history hooks

- app/assets/page-client.tsx
This PR leverages the changes in https://github.com/renegade-fi/typescript-sdk/pull/149 to set a 1000-task limit for the task history fetch used to display transfer history. Using this large constant is a stopgap solution until historical state is fully integrated, which will support pagination at the API layer.
This was tested by running a local frontend against the mainnet stack, where I asserted that I was able to fetch transfer history from further back for my wallet.
> app: assets: set 1000-task limit for transfer history fetch

- hooks/use-order-history.ts
- hooks/use-task-history.ts
- package.json
- pnpm-lock.yaml
This PR ensures that the custom `useTaskHistory` and `useOrderHistory` hooks properly use the parameters passed in to them.
> hooks: accept parameters in useTaskHistory & useOrderHistory

- app/trade/[base]/components/order-details/cancel-button.tsx
- hooks/use-prepare-cancel-order.ts
This PR fixes a bug where the query function for the cancel order body request returned undefined, which is invalid behavior according to Tanstack Query docs.
> cancel order: fix query for cancel order req body

- app/components/invalidate-queries.tsx
- lib/query.ts
- providers/query-provider.tsx
This PR prevents price query invalidation in the global invalidation rule because we depend on WebSocket messages for price data, not HTTP requests.
> query: prevent price query invalidation

- components/animated-price-status.tsx
This PR allows prices a chance to update before displaying stale status.
> price query: Use optimistic price status on mount

- providers/wagmi-provider/wagmi-provider.tsx
This PR attempts to smoothen UX regarding browser extension wallet connection. When the wallet disconnects, we attempt to reconnect to the last connected wallet. If this fails, we fully disconnect.
> wagmi: reconnect on out of sync error

- app/api/faucet/route.ts
- app/components/wallet-sidebar/arbitrum-wallet-actions-dropdown.tsx
- app/components/wallet-sidebar/renegade-wallet-actions-dropdown.tsx
- components/dialogs/transfer/helpers.ts
- components/dialogs/transfer/usdc-form.tsx
- hooks/use-cancel-all-orders.ts
- hooks/use-deposit.ts
- hooks/use-prepare-cancel-order.ts
- hooks/use-prepare-create-order.ts
- hooks/use-sign-in-and-connect.ts
- hooks/use-withdraw.ts
- hooks/usePrepareDeposit.ts
- hooks/usePrepareWithdraw.ts
- lib/viem.ts
- providers/renegade-provider/renegade-provider.tsx
- providers/wagmi-provider/config.ts
This PR ensures the client environment is aware that configs may now be undefined. Worth noting that this is mostly to appease the Typescript compiler: most of these branches are impossible to reach if the config is undefined. Ideally we make Typescript aware of this using type narrowing on the config object itself, but this is sufficient for a straightforward and simple implementation.
> finish guarding undefined config

- app/api/get-logs/route.ts
- app/api/stats/set-inflow-kv/route.ts
- app/api/stats/tvl/route.ts
- app/api/stats/tvl/usd/route.ts
- components/dialogs/onboarding/sign-in-dialog.tsx
- components/dialogs/transfer/default-form.tsx
- components/dialogs/transfer/usdc-form.tsx
- components/dialogs/transfer/weth-form.tsx
- hooks/use-chain.ts
- hooks/use-deposit.ts
- lib/viem.ts
- providers/renegade-provider/config.ts
This PR begins the process of obviating the chain ID from environment variables. This first phase focuses on static parameters derived from the chain ID such as the Permit2 contract address.
This relies on https://github.com/renegade-fi/typescript-sdk/pull/212
> begin removing chain id env var: use sdk config

- app/layout.tsx
- components/dialogs/onboarding/sign-in-dialog.tsx
- components/dialogs/transfer/use-bridge-quote.ts
- hooks/use-in-relayer.ts
- hooks/use-renegade-status.ts
- hooks/use-sign-in-and-connect.ts
- hooks/use-wallets.ts
- lib/viem.ts
- package.json
- pnpm-lock.yaml
- providers/renegade-provider/config.ts
- providers/renegade-provider/renegade-provider.tsx
- providers/state-provider/cookie-actions.ts
- providers/state-provider/server-store.ts
- providers/wagmi-provider/config.ts
This PR begins the process of lifting Renegade wallet state up from the config object to the server store that exists in the client. This is done to improve ergonomics of managing this state that is core to every part of the app; it was difficult to deal with as it existed within this `config` object. Now, we store it at the top level ServerStoreProvider (which uses the same storage as `config` does i.e. zustand with persist middleware) which allows first-class reactivity and hydration.
> persistence: begin migration to server store

- components/dialogs/onboarding/sign-in-dialog.tsx
- providers/renegade-provider/renegade-provider.tsx
- providers/wagmi-provider/theme.ts
- providers/wagmi-provider/wagmi-provider.tsx
This PR implements effects to keep Renegade wallet state in sync with Wagmi state. While Renegade state is derived from Wagmi state, it can be modified outside the scope of the app (in the extension, auto-lock, etc.), so we listen for these events and update Renegade wallet state accordingly.
> state: sync Wagmi state with Renegade state

- app/components/wallet-sidebar/arbitrum-wallet-actions-dropdown.tsx
- app/components/wallet-sidebar/renegade-wallet-actions-dropdown.tsx
- components/dialogs/transfer/default-form.tsx
- components/dialogs/transfer/usdc-form.tsx
- components/dialogs/transfer/weth-form.tsx
- hooks/use-chain-id.ts
- hooks/use-deposit.ts
- hooks/use-sign-in-and-connect.ts
- hooks/use-wallets.ts
- providers/renegade-provider/renegade-provider.tsx
This PR replaces invocations of the `disconnect` action with `resetWallet` which clears the server store's wallet field. We also remove unnecessary invocations of the wagmi `disconnect` action, only forcibly disconnecting the browser wallet if the user decides to.
> replace renegade disconnect with resetWallet

- app/api/tokens/get-combined-balances/route.ts
- app/trade/[base]/components/bbo-marquee.tsx
- app/trade/[base]/page-client.tsx
- app/trade/[base]/page.tsx
- app/trade/[base]/utils.ts
- components/animated-price.tsx
- lib/price-status.ts
- lib/query.ts
- lib/token.ts
- lib/utils.ts
- middleware.ts
- package.json
- pnpm-lock.yaml
- providers/state-provider/server-store.ts
This PR beings the migration to relying on mints to uniquely identify tokens at the top level. The rationale being it's important to avoid panics and optional values where possible in the frontend, and requiring `chainID` anywhere we needed to index the token remap was too much of a footgun, especially when factoring in switching chains and other wagmi state transitions that can happen outside the purview of the interface. 
This way, the address is **always** available and correct.
The important changes are in util.ts: we add logic to parse the base mint from either a ticker or an address in the path.
> begin migration to addres-specified base token

- app/trade/[base]/page-client.tsx
- app/trade/[base]/page.tsx
- app/trade/[base]/utils.ts
- hooks/use-resolve-pair.ts
- lib/token.ts
- package.json
- pnpm-lock.yaml
- providers/wagmi-provider/config.ts
This PR simplifies the token resolution process: we now accept only valid tickers from the URL path. These are then resolved to an address client-side using the Renegade chain ID if the ticker exists on both Arbitrum and Base. Otherwise, we pass the first matched address and rely on the switch chain button from #282 to prompt the user to switch to the correct chain to place an order.
We still store the last resolved address in cookie storage as a fallback.
> fix token resolution

- app/components/header.tsx
- app/trade/[base]/components/new-order/amount-shortcut-button.tsx
- app/trade/[base]/components/new-order/assets-section.tsx
- app/trade/[base]/components/new-order/new-order-form.tsx
- app/trade/[base]/page-client.tsx
- app/trade/[base]/page.tsx
- app/trade/[base]/utils.ts
- components/dialogs/order-stepper/desktop/steps/default.tsx
- components/dialogs/order-stepper/mobile/steps/confirm.tsx
- components/dialogs/order-stepper/mobile/steps/default.tsx
- env/schema.ts
- hooks/use-order-value.ts
- providers/state-provider/cookie-storage.ts
- providers/state-provider/schema.ts
- providers/state-provider/server-store.ts
- providers/wagmi-provider/wagmi-provider.tsx
This PR ensures the state read from cookies to initialize the server store is validated to prevent panics due to corrupted state.
We also move `baseMint` and `quoteMint` to the top level of the state object to obviate potential issues due to overwriting slices of state.
> server store: validate initial state using zod

- app/api/alchemy-transfers.ts
- app/api/get-logs/route.ts
- app/api/stats/constants.ts
- app/api/stats/external-transfer-logs/route.ts
- app/api/stats/net-flow/route.ts
- app/api/stats/set-inflow-kv/route.ts
- app/api/utils.ts
- app/stats/charts/inflows-chart.tsx
- app/stats/hooks/use-external-transfer-data.ts
- app/stats/page-client.tsx
- env/client.ts
- env/server.ts
- lib/viem.ts
- vercel.json
This PR modifies the route handlers responsible for transfer stats to be chain-aware. We switched to using Alchemy's getAssetTransfer RPC instead of fetching ExternalTransfer logs because the Base contract does not emit them.
I also backfilled the KV store with Arbitrum + Base transfer data to test + migrate.
> stats: transfers: chain-specific erc20 transfer fetching

- app/trade/[base]/components/mobile-asset-price-accordion.tsx
- components/animated-price.tsx
- hooks/use-price-query.ts
- hooks/use-price-websocket.ts
- lib/format.ts
This PR introduces a custom formatter for currencies that takes into account the value being formatted to choose decimal counts that are not too reductive. Fixes an issue where sub-cent token prices were being rounded to '<$0.01'.
> price display: dynamic formatting based on value

- app/components/wallet-sidebar/index.tsx
- app/layout.tsx
This PR disables sidebar close on wallet disconnect (either renegade or wagmi).
> remove wallet sidebar close on disconnect

- app/components/wallet-sidebar/index.tsx
- app/layout.tsx
- app/trade/[base]/components/new-order/new-order-form.tsx
- components/dialogs/transfer/default-form.tsx
- hooks/use-wallets.ts
- package.json
- pnpm-lock.yaml
This PR fixes an issue where the base mint was not being synced between the server state and the order form state.
In the future, we should remove the form entirely and instead use controlled components deriving/setting state in the server store. Using an effect to keep two pieces of state is an anti-pattern and leads to bugs exactly like this one.
> sync order form with server store

- app/components/chain-selector.tsx
- app/components/header.tsx
- app/components/wallet-sidebar/index.tsx
- app/layout.tsx
- app/trade/[base]/components/new-order/new-order-form.tsx
- components/dialogs/transfer/default-form.tsx
- env/schema.ts
- hooks/use-wallets.ts
- package.json
- pnpm-lock.yaml
- providers/state-provider/cookie-storage.ts
- providers/state-provider/hooks.ts
- providers/state-provider/schema.ts
- providers/state-provider/server-store.ts
This PR adds a top level chain id to the server store type which will be used as the source of truth of chain id throughout the app. 
This change is motivated by the desire to seamlessly switch between wallets based on chain id. We need to store a {seed, id} combo for each chain id, along with the current chain id the user has selected.
> server store: add top level chain id, multiple wallets

- app/components/wallet-sidebar/renegade-wallet-actions-dropdown.tsx
- app/trade/[base]/components/order-details/cancel-button.tsx
- components/dialogs/order-stepper/mobile/steps/confirm.tsx
- components/wallet-index-check.tsx
- hooks/mutation/use-cancel-order.ts
- providers/state-provider/hooks.ts
This PR adds reactive `useCancelOrder` hook. It also completely migrates from the old useConfig hook to the new one.
> cancel order: use reactive hook

- app/components/track-last-visit.tsx
- app/components/wallet-sidebar/hooks/use-unviewed-fills.ts
- app/components/wallet-sidebar/hooks/use-viewed-fills.ts
- app/trade/[base]/components/favorites-banner.tsx
- app/trade/[base]/components/new-order/new-order-form.tsx
- app/trade/[base]/page-client.tsx
- components/dialogs/token-select-dialog.tsx
- components/dialogs/transfer/default-form.tsx
- components/dialogs/transfer/usdc-form.tsx
- components/dialogs/transfer/weth-form.tsx
- providers/state-provider/hooks.ts
- providers/state-provider/server-store.ts
This PR enforces the rule of using selectors to access items in the store, rather than accessing the whole state object and restructuring. This ensure we avoid unnecessary re-renders due to React's shallow equality checker.
> storage: always use selectors

- app/api/savings/helpers.ts
- app/api/savings/route.ts
- app/stats/chain-selector.tsx
- app/stats/charts/inflows-chart.tsx
- app/stats/charts/tvl/tvl-section.tsx
- app/stats/charts/volume-chart.tsx
- components/dialogs/transfer/transfer-form.tsx
- hooks/savings/savingsQueryOptions.ts
- hooks/savings/use-savings-across-fills-query.ts
- hooks/savings/use-savings-query.ts
- hooks/use-predicted-fees.ts
- providers/wagmi-provider/wagmi-provider.tsx
This PR slightly adjusts the way we retrieve order book snapshots: previously we would specify a minute long timeframe to retrieve the most recent order book snapshot. This would error in the scenario wherein Amberdata had a gap of order book data for the period. This would result in a savings value never being calculated. I found these data gaps to not be uncommon, no matter how much time had passed certain timeframes never yielded results. We now fetch snapshots without a time frame and rely on Amberdata to return the most recent one. We then proceed in the same way to fetch and apply the most recent order book updates. This has proven to result in savings calculations much more consistently.
Chart headers now reflect the current chain, if specified, both in the cumulative values and …
> base: misc fixes

- providers/state-provider/server-store.ts
This PR ensures a default chain is chosen from an environment-aware array of chains.
> server store: env-specific default chain id

- lib/constants/storage.ts
- providers/state-provider/cookie-storage.ts
- providers/state-provider/server-store.ts
This PR ensures safe migrations from old storage schemas by using zustand-native options `version` and `migrate` to cleanly wipe returning users' state. 
We also add a version check to `cookieToInitialState` since migrations only run on rehydration, not initial state passed in. This obviates the need for a Zod guard in `createStore`, as any initial state parsed from cookies will necessarily be either undefined or of the correct shape for the current version.
> server store: add rules for migrating properly

- hooks/use-order-table-data.ts
This PR filters out zero orders from the wallet object before syncing with order history from the HSE. This ensures the scenario where the HSE contains status `Created` but the order has amount 0 is covered, as per Joey's report.
> order table: filter zero orders from wallet'

- app/api/stats/constants.ts
- app/api/stats/helpers.ts
- app/api/stats/set-inflow-kv/route.ts
This PR adds a validation step when scraping external transfer data that checks that a given transaction was a deposit or a withdraw from the darkpool. This is necessary because the `alchemy_getAssetTransfers` returns txns involved in an external match in addition to deposits/withdrawals. Validating the log count seems to be accurate, but in the future we may want to emit `ExternalTransfer` event from Base contracts (like we do in Arbitrum contracts).
A separate script will have to be run to validate existing data.
> stats: validate tx is deposit/withdraw

- app/page.tsx
- app/trade/[base]/page.tsx
- app/trade/page.tsx
This PR ensures search parameters are preserved upon redirect from /trade to /trade/[base]
> trade: preserve chain param during redirect
