- components/dialogs/transfer/transfer-dialog.tsx
This PR allows for withdrawing the full balance, even if the amount is less than `MIN_TRANSFER_AMOUNT` as the relayer allows for this.
Tested using the frontend on mainnet.
> transfer dialog: enable withdraw full balance

- app/components/mobile-nav-sheet.tsx
- app/components/task-toaster.tsx
- app/trade/[base]/components/new-order/new-order-form.tsx
- app/trade/[base]/components/order-details/cancel-button.tsx
- app/trade/[base]/components/order-details/details-content.tsx
- app/trade/[base]/components/order-details/empty-content.tsx
- app/trade/[base]/components/order-details/order-details-sheet.tsx
- components/dialogs/order-stepper/desktop/steps/default.tsx
- components/dialogs/order-stepper/mobile/new-order-stepper.tsx
- components/dialogs/order-stepper/mobile/steps/confirm.tsx
- components/dialogs/order-stepper/mobile/steps/default.tsx
- components/dialogs/order-stepper/mobile/steps/success-without-savings.tsx
- components/dialogs/sign-in-dialog.tsx
- components/dialogs/token-select-dialog.tsx
- components/dialogs/transfer/transfer-dialog.tsx
- middleware.ts
This PR enables mobile with full screen dialogs. Also fixes scrolling and layout issues. Standardizes "Close" button across dialogs.
> mobile: reenable drawerless

- app/api/stats/historical-volume-kv/route.ts
This PR fetches historical volume data from the KV store using pipeline to use one network request.
> stats: fetch using pipeline-nocache

- app/api/stats/external-transfer-logs/route.ts
- app/api/stats/net-flow/route.ts
- app/api/stats/set-net-flow-kv/route.ts
This PR ensures get requests to the KV db are not cached and pipelined to reduce the number of requests over the wire.
> stats: fetch kv rest api with no-store

- app/trade/[base]/components/settings-dropdown.tsx
This PR reverts the "Remember me" checkbox style in the settings dropdown.
> settings dropdown: revert checkbox style

- app/stats/charts/inflows-chart.tsx
This PR derives net flow from chart data, whereas before it was derived from a cron job calculating it from KV store data which frequently was out of sync.
> inflows chart: derive net flow from chart data

- app/api/tokens/get-combined-balances/route.ts
- app/api/utils.ts
- app/assets/assets-table/columns.tsx
- app/assets/assets-table/data-table.tsx
- app/assets/page-client.tsx
- components/dialogs/token-select.tsx
- components/dialogs/transfer/bridge-prompt.tsx
- components/dialogs/transfer/default-form.tsx
- components/dialogs/transfer/helpers.ts
- components/dialogs/transfer/usdc-form.tsx
- components/dialogs/transfer/weth-form.tsx
- components/ui/hover-card.tsx
- hooks/use-combined-balances.ts
- lib/constants/tooltips.ts
- lib/token.ts
- package.json
- pnpm-lock.yaml
- providers/wagmi-provider/wagmi-provider.tsx
This PR adds Ethereum balances to the transfer dialog in addition to a link to the canonical Arbitrum bridge for users to bridge funds from L1 -> L2.
> transfer dialog: arbitrum bridge and merged balances

- components/dialogs/transfer/default-form.tsx
- components/dialogs/transfer/hooks/use-chain-balance.tsx
- components/dialogs/transfer/hooks/use-renegade-balance.tsx
- components/dialogs/transfer/hooks/use-token.ts
- components/dialogs/transfer/transfer-details-page.tsx
- components/dialogs/transfer/usdc-form.tsx
- components/dialogs/transfer/weth-form.tsx
This PR refactors balance fetching and formatting code into hooks that are used across transfer forms.
> transfer dialog: refactor shared logic into hooks

- app/trade/[base]/components/charts/tradingview/datafeed.ts
- app/trade/[base]/components/charts/tradingview/helpers.ts
This PR updates the Amberdata integration according to their migration found in their docs.
> price chart: update amberdata integration

- app/orders/data-table.tsx
- app/trade/[base]/components/new-order/new-order-form.tsx
- app/trade/[base]/components/order-details/cancel-button.tsx
- components/ui/responsive-tooltip.tsx
This PR fixes various hydration issues due to invalid HTML tag usage.
> chore: fix hydration issues

- app/components/deposit-banner.tsx
This PR fixes Typescript types.
> deposit banner: fix types

- app/api/tokens/get-combined-balances/route.ts
- app/api/utils.ts
- hooks/use-combined-balances.ts
This PR adds Solana USDC to the list of balances to fetch and merge for use throughout the interface. Also parallelizes RPC calls because the function was taking 1.5s+ to execute.
> api: combined balances: parallelize and add Solana USDC

- components/dialogs/token-select.tsx
- components/dialogs/transfer/transfer-form.tsx
- components/dialogs/transfer/weth-form.tsx
- hooks/use-assets-table-data.ts
- hooks/use-combined-balances.ts
- hooks/use-on-chain-balances.ts
- lib/token.ts
- lib/viem.ts
This PR adds a check so that multi-chain balances will not be fetched if in testnet. Bridging/swapping is also disabled on testnet.
> testnet: catch up testnet to main

- components/dialogs/transfer/hooks/use-chain-balance.tsx
- components/dialogs/transfer/usdc-form.tsx
- components/dialogs/transfer/weth-form.tsx
- hooks/use-on-chain-balances.ts
- hooks/use-wallets.ts
- providers/wagmi-provider/config.ts
- providers/wagmi-provider/wagmi-provider.tsx
This PR specifies the Arbitrum config when fetching native balance to avoid a scenario where the wrong balance is fetched.
> weth form: specify chain when fetching native balance

- app/actions.ts
- app/api/cookie/set-base/route.ts
- app/api/delete-cookie/route.ts
- app/components/header.tsx
- app/layout.tsx
- app/trade/[base]/actions.ts
- app/trade/[base]/components/new-order/new-order-form.tsx
- app/trade/[base]/page-client.tsx
- middleware.ts
- providers/renegade-provider/renegade-provider.tsx
- providers/side-provider.tsx
- providers/wagmi-provider/wagmi-provider.tsx
This PR fixes persistent base so that the cookie is properly updates and read.
> middleware: fix persistent base

- lib/format.ts
This PR uses more standard formatting rules for numbers and currencies.
> format: use standard formatting rules

- app/components/mobile-nav-sheet.tsx
- app/trade/[base]/components/new-order/fees-sections.tsx
- app/trade/[base]/components/new-order/new-order-form.tsx
- app/trade/[base]/components/new-order/new-order-panel.tsx
- app/trade/[base]/components/order-details/empty-content.tsx
- components/did-you-know-content.tsx
- lib/constants/articles.ts
This PR colocates all help center articles into one constants file.
> help center: store articles in constants

- app/assets/assets-table/columns.tsx
- app/assets/assets-table/data-table.tsx
- app/assets/history-table/columns.tsx
- app/assets/history-table/data-table.tsx
- app/assets/page-client.tsx
- app/components/footer.tsx
- app/orders/columns.tsx
- app/orders/data-table.tsx
- app/trade/[base]/components/bbo-marquee.tsx
- app/trade/[base]/components/new-order/amount-shortcut-button.tsx
- app/trade/[base]/components/new-order/assets-section.tsx
- app/trade/[base]/components/new-order/deposit-warning.tsx
- app/trade/[base]/components/new-order/fees-sections.tsx
- app/trade/[base]/components/new-order/max-orders-warning.tsx
- app/trade/[base]/components/new-order/new-order-form.tsx
- app/trade/[base]/components/new-order/no-balance-slot-warning.tsx
- app/trade/[base]/components/order-details/columns.tsx
- app/trade/[base]/components/order-details/details-content.tsx
- app/trade/[base]/components/order-details/empty-content.tsx
- app/trade/[base]/components/order-details/insufficient-warning.tsx
- components/copy-to-clipboard.tsx
- components/dialogs/order-stepper/desktop/steps/default.tsx
- components/dialogs/transfer/max-balances-warning.tsx
- components/dialogs/transfer/review-bridge.tsx
- components/dialogs/transfer/review-wrap.tsx
- components/dialogs/transfer/weth-form.tsx
- components/ui/button.tsx
- components/ui/tooltip.tsx
This PR removes unnecessary `p` tags in instances of `TooltipContent` and standardizes usage within vertical layouts.
> tooltips: fix margin issue with tooltips

- components/dialogs/order-stepper/external-matches-section.tsx
This PR fixes positioning and toggling of external match popover on mobile.
> new order form: fix external orders popover on mobile

- lib/query.ts
- lib/utils.ts
- package.json
- pnpm-lock.yaml
This PR uses the new `getDefaultQuotes` method in place of the old `DEFAULT_QUOTE` constant
> lib: utils, query: use getDefaultQuotes method

- components/dialogs/transfer/helpers.ts
- components/dialogs/transfer/usdc-form.tsx
- components/dialogs/transfer/use-bridge-quote.ts
This PR ensures the recipient address of a USDC bridge transfer is the address associated with the connected Renegade wallet.
> usdc form: safeguard bridge recipient by verifying Renegade root

- components/dialogs/order-stepper/external-matches-section.tsx
This PR rewords external match explainer copy.
> order form: fixup external match copy

- app/stats/charts/time-to-fill-card.tsx
- app/trade/[base]/components/new-order/new-order-form.tsx
- components/dialogs/order-stepper/desktop/steps/default.tsx
- hooks/use-fees-check.ts
- hooks/use-order-value.ts
- hooks/use-predicted-fees.ts
- package.json
- pnpm-lock.yaml
This PR adds an estimated receive value row to the order creation form.
I also changed some variable names to be more accurate. Prettier was also updated to format the files properly.
> new order: add estimated receive + tooltip to new order flow

- components/animated-price-status.tsx
- components/animated-price.tsx
- lib/utils.ts
This PR temporarily sets Coinbase prices to "NO DATA" while the price reporter is being fixed.
> bbo banner: temp coinbase no data

- app/api/amberdata/helpers.ts
- app/api/proxy/amberdata/route.ts
- app/api/savings/helpers.ts
This PR ensures compression is enabled for all requests to Amberdata as per their message.
> amberdata: Use gzip compression for requests

- components/animated-price-status.tsx
- components/animated-price.tsx
- hooks/use-price-query.ts
- lib/price-status.ts
This PR fixes a bug where the price status would not react to entering a "stale" state.
> bbo-banner: fix price status logic

- components/animated-price-status.tsx
- components/animated-price.tsx
This PR removes the temporary No Data label for Coinbase prices.
> bbo banner: remove temp coinbase no data label

- app/trade/[base]/components/new-order/new-order-form.tsx
This PR fixes a bug wherein the form would reset to out of date default values, causing the "side" value to be set incorrectly after placing an order.
> order form: prevent side toggle on form reset

- package.json
- pnpm-lock.yaml
- providers/wagmi-provider/wagmi-provider.tsx
This PR bumps the React SDK to a version with better handling of WASM initialization and WS unsubscribing.
> chore: bump react sdk

- app/stats/charts/inflows-chart.tsx
This PR reduces gap between bars so inflows chart renders properly (many data points causing overlap).
> stats: inflow-chart: reduce bar gap

- package.json
- pnpm-lock.yaml
This PR runs the Next upgrade CLI tool to bump Next + React to latest versions.
> chore: bump next, react

- components/dialogs/transfer/transfer-form.tsx
- env/client.ts
- lib/viem.ts
This PR enables depositing + withdrawing on base sepolia.
> balance ops: deposit and withdraw working

- hooks/use-price-queries.ts
- hooks/use-price-query.ts
- lib/query.ts
- lib/viem.ts
- package.json
- pnpm-lock.yaml
This PR migrates to the client from `@renegade-fi/price-reporter`.
> price-reporter: use PriceReporterClient

- env/client.ts
- hooks/use-price-websocket.ts
- package.json
- pnpm-lock.yaml
This PR removes price reporter url from env variables.
> env: remove price reporter from process

- env/client.ts
- hooks/use-public-client.ts
- providers/renegade-provider/renegade-provider.tsx
This PR cleans up unused env vars.
> env: remove unused vars

- app/components/wallet-sidebar/arbitrum-wallet-actions-dropdown.tsx
- app/components/wallet-sidebar/renegade-wallet-actions-dropdown.tsx
- components/dialogs/transfer/default-form.tsx
- components/dialogs/transfer/network-select.tsx
- components/dialogs/transfer/usdc-form.tsx
- components/dialogs/transfer/weth-form.tsx
- hooks/use-chain-id.ts
- hooks/use-deposit.ts
- hooks/use-sign-in-and-connect.ts
- hooks/use-wallets.ts
- providers/renegade-provider/renegade-provider.tsx
This PR removes muted text style from the default state of the network select component.
> fix network select default style

- app/api/tokens/get-combined-balances/route.ts
- app/components/wallet-sidebar/arbitrum-wallet-actions-dropdown.tsx
- app/components/wallet-sidebar/renegade-wallet-actions-dropdown.tsx
- components/dialogs/transfer/default-form.tsx
- components/dialogs/transfer/network-select.tsx
- components/dialogs/transfer/usdc-form.tsx
- components/dialogs/transfer/weth-form.tsx
- hooks/use-chain-id.ts
- hooks/use-deposit.ts
- hooks/use-sign-in-and-connect.ts
- hooks/use-wallets.ts
- providers/renegade-provider/renegade-provider.tsx
This PR scopes the `/get-combined-balance` route to only fetch balances for arbitrum tokens. This route is not used on either testnet or Base.
> scope get combined balances to only arbitrum

- app/components/header.tsx
- app/stats/charts/time-to-fill-card.tsx
- app/stats/charts/token-select.tsx
- app/stats/hooks/use-time-to-fill.ts
- app/stats/hooks/use-tvl-data.ts
This PR fixes time to fill and tvl data usage post migration to base mint.
> fix time to fill and tvl data stats

- components/dialogs/token-select-dialog.tsx
This PR fixes a bug regarding dead clicks in the token select dialog due to padding around the <Link>.
> token select: fix dead click

- app/components/wallet-sidebar/index.tsx
- app/layout.tsx
- components/dialogs/token-select-dialog.tsx
- hooks/use-is-base.ts
- providers/solana-provider.tsx
- providers/wagmi-provider/config.ts
This PR disconnects from a connected solana wallet if the current chain is Base. Also hides the Solana wallet prompt on Base.
> solana: disconnect and hide when on base

- app/trade/[base]/components/new-order/fees-sections.tsx
- hooks/use-savings-across-fills-query.ts
- hooks/use-savings-query.ts
This PR disables savings calculations on Base. In a future PR we will compute based on order book depth of various canonical exchanges.
> savings query: disable on base

- app/components/header.tsx
- app/trade/[base]/page.tsx
- app/trade/[base]/utils.ts
- app/trade/page.tsx
This PR adds redirects for QoL.
> routing: redirect / and /trade to fallback ticker

- app/assets/assets-table/columns.tsx
- app/components/deposit-banner.tsx
- components/dialogs/transfer/bridge-prompt.tsx
- components/dialogs/transfer/default-form.tsx
- hooks/use-chain-name.ts
- lib/constants/tooltips.ts
This PR removes hardcoded "Arbitrum" labels in favor of dynamically choosing the right chain name.
> labels: remove hardcoded arbitrum labels

- app/components/wallet-sidebar/index.tsx
- app/layout.tsx
- hooks/use-wallets.ts
- package.json
- pnpm-lock.yaml
This PR changes wallet button title from "... Address" to "... Wallet"
> address -> wallet title

- app/stats/chain-selector.tsx
- app/stats/charts/tvl-chart.tsx
- app/stats/hooks/use-tvl-data.ts
- app/stats/hooks/use-tvl.ts
- app/stats/page-client.tsx
- hooks/use-price-query.ts
- hooks/use-prices-snapshot.ts
- lib/query.ts
This PR begins the migration to a merged TVL view. Note that `tvl-chart.tsx` is deleted in #322 so it doesn't require review.
> stats: merge tvl

- app/stats/charts/volume-chart.tsx
- app/stats/hooks/use-volume-data.ts
- app/stats/page-client.tsx
This PR ensures the volume chart is able to show merged volume when necessary.
> stats: merged volume chart

- app/stats/chain-selector.tsx
- app/stats/charts/inflows-chart.tsx
- app/stats/hooks/use-external-transfer-data.ts
- app/stats/page-client.tsx
This PR ensures the transfers chart can show merged transfers when needed.
> stats: merged transfers chart

- components/dialogs/order-stepper/desktop/new-order-stepper.tsx
- components/dialogs/order-stepper/desktop/steps/default.tsx
- components/dialogs/order-stepper/external-matches-section.tsx
- components/dialogs/order-stepper/mobile/steps/confirm.tsx
- hooks/use-prepare-create-order.ts
- providers/state-provider/schema.ts
- providers/state-provider/server-store.ts
This PR ensures external matches are enabled by default.
> external matches: enable by default

- app/components/chain-selector.tsx
- app/components/header.tsx
- app/components/wallet-sidebar/recent-fills-menu-item.tsx
- app/components/wrong-pair-network-modal.tsx
- app/trade/[base]/components/charts/price-chart.tsx
- app/trade/[base]/page-client.tsx
- providers/state-provider/server-store.ts
This PR fixes a number of UI issues:
- price chart rerendering even though token does not change
- chain switch on a page other than the trade page
- nav bar items not respecting chain id, leading to incorrect token modal
- added network logos to chain selector
> ui: chain selector, wrong chain fixes

- app/api/savings/route.ts
- app/components/wallet-sidebar/recent-fills-menu-item.tsx
- app/orders/columns.tsx
- app/trade/[base]/components/new-order/fees-sections.tsx
- components/dialogs/order-stepper/desktop/new-order-stepper.tsx
- hooks/savings/savingsQueryOptions.ts
- hooks/savings/use-savings-across-fills-query.ts
- hooks/use-predicted-fees.ts
- lib/constants/protocol.ts
This PR adds tooltips displaying relative fee / savings values.
> fee + savings: display relative fee and savings as tooltip

- providers/state-provider/server-store-provider.tsx
- providers/state-provider/server-store.ts
This PR adds logs to server store init/setters.
> add logs to server store

- app/components/chain-selector.tsx
- app/components/wrong-network-modal.tsx
- app/trade/[base]/page-client.tsx
- app/trade/[base]/page.tsx
- lib/constants/storage.ts
- package.json
- pnpm-lock.yaml
- providers/state-provider/server-store-provider.tsx
- providers/state-provider/server-store.ts
- providers/wagmi-provider/wagmi-provider.tsx
This PR reads `chain` search parameter and uses it as the default chain when initializing an empty server store.
> chain: use chain search param in initial state
